concurrent = 1
check_interval = 0

[[runners]]
  name = "runner2"
  url = "http://gitlab.services.alin.be"
  token = "2d9278e1420545d396b0a33b9e878d"
  executor = "docker"
  cache_dir = "\"cache\""
  [runners.docker]
    tls_verify = false
    image = "alpine:3.7"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
