# Don't edit this file, user DockerfileTemplate and buildImage.sh
###############################################
FROM registry.services.alin.be/gitlab/gitlab-runner:alpine-v10.8.0
COPY localtime /etc/localtime
#HEALTHCHECK --interval=10s --timeout=10s --retries=3 CMD curl -f http://localhost:9000/minio/index.html || exit 1
